Prefer printf to echo

diff --git a/stow/.local/bin/br b/stow/.local/bin/br
--- a/stow/.local/bin/br
+++ b/stow/.local/bin/br
@@ -13,7 +13,7 @@ Options:
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
@@ -21,7 +21,7 @@ while getopts ":nh" option; do
     case $option in
     n) dry_run=1 ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
@@ -40,7 +40,7 @@ dst_list=$temp_dir/dst
 
 for file in "$@"; do
     if [[ -e $file ]]; then
-        echo "$file"
+        printf "%s\n" "$file"
     fi
 done >"$src_list"
 
@@ -68,5 +68,5 @@ for ((i = 0; i < ${#dst_lines[@]}; i += 1)); do
         mv -i -T "$src" "$dst"
     fi
 
-    echo "$dst"
+    printf "%s\n" "$dst"
 done
diff --git a/stow/.local/bin/brseq b/stow/.local/bin/brseq
--- a/stow/.local/bin/brseq
+++ b/stow/.local/bin/brseq
@@ -29,7 +29,7 @@ The following placeholders are recognized in FORMAT:
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
@@ -44,7 +44,7 @@ while getopts ":f:s:i:W:wnh" option; do
     w) seq_options+=(-w) ;;
     n) dry_run=1 ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
@@ -93,5 +93,5 @@ while IFS= read -r -d $'\n' num; do
         mv -i -T "$src" "$dst"
     fi
 
-    echo "$dst"
+    printf "%s\n" "$dst"
 done < <(seq "${seq_options[@]}" "$start_num" "$increment" "$end_num")
diff --git a/stow/.local/bin/queue b/stow/.local/bin/queue
--- a/stow/.local/bin/queue
+++ b/stow/.local/bin/queue
@@ -22,14 +22,14 @@ Items are popped from the top and added to the bottom.
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s\n" "$*" >&2
     exit 1
 }
 
 while getopts ":h" option; do
     case $option in
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
@@ -79,7 +79,7 @@ do_pop() {
     # Comment out the line that was just retrieved.
     sed -E -i "${line_num}s/^\s*/# /" "$queue"
 
-    echo "$line"
+    printf "%s\n" "$line"
 }
 
 do_clear() {
diff --git a/stow/.local/bin/yank b/stow/.local/bin/yank
--- a/stow/.local/bin/yank
+++ b/stow/.local/bin/yank
@@ -14,7 +14,6 @@ Usage:
 Options:
     -R              perform action on all existing registers
     -r NAME         perform action on register (can use multiple times)
-
     -C DIRECTORY    directory in which to store registers
                     (default: $cache_dir)
 
@@ -34,7 +33,7 @@ When operating on all registers with -R, 'default' will be included.
 "
 
 die() {
-    echo "ERROR: $*" >&2
+    printf "ERROR: %s" "$*" >&2
     exit 1
 }
 
@@ -86,7 +85,7 @@ while getopts ":r:RC:h" option; do
         ;;
     C) cache_dir=$OPTARG ;;
     h)
-        echo "$usage"
+        printf "%s\n" "$usage"
         exit
         ;;
     *) die "Invalid option '$OPTARG'" ;;
