Tinkering

diff --git a/stow/.local/bin/br b/stow/.local/bin/br
--- a/stow/.local/bin/br
+++ b/stow/.local/bin/br
@@ -2,14 +2,14 @@
 
 set -eu
 
-me=${0##*/}
+name=${0##*/}
 usage="Rename files using your preferred editor.
 
-Usage: $me [-h] [-n] FILE...
+Usage:
+    $name [-n] FILE...
 
 Options:
-    -h    show this help message
-    -n    show the renamed files without actually renaming them
+    -n    dry-run (no changes are made)
 "
 
 usage() {
@@ -18,31 +18,32 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
-noop=
-unset OPTIND OPTARG
-while getopts ":hn" option; do
+while getopts ":nh" option; do
     case $option in
-    n) noop=1 ;;
+    n) dry_run=1 ;;
     h) usage ;;
-    *) die "invalid option: $OPTARG" ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
-unset option OPTIND OPTARG
 
-(($# == 0)) && die "no files to rename"
+if (($# == 0)); then
+    die "no files to rename"
+fi
 
-temp_dir=$(mktemp -d -t "${me}.XXXXXXXXXX")
+temp_dir=$(mktemp -d -t "${name}.XXXXXXXXXX")
 trap 'rm -rf "$temp_dir"' INT TERM EXIT
 
 src_list=$temp_dir/src
 dst_list=$temp_dir/dst
 
 for file in "$@"; do
-    [[ -e $file ]] && echo "$file"
+    if [[ -e $file ]]; then
+        echo "$file"
+    fi
 done >"$src_list"
 
 cp "$src_list" "$dst_list"
@@ -53,16 +54,18 @@ readarray -t src_lines <"$src_list"
 readarray -t dst_lines <"$dst_list"
 
 if ((${#src_lines[@]} != ${#dst_lines[@]})); then
-    die "lines were added or removed"
+    die "Lines were added or removed"
 fi
 
 for ((i = 0; i < ${#dst_lines[@]}; i += 1)); do
     src=${src_lines[$i]}
     dst=${dst_lines[$i]}
 
-    [[ "$src" == "$dst" ]] && continue
+    if [[ $src == "$dst" ]]; then
+        continue
+    fi
 
-    if [[ -z $noop ]]; then
+    if [[ -z $dry_run ]]; then
         mkdir -p "$(dirname "$dst")"
         mv -i -T "$src" "$dst"
     fi
diff --git a/stow/.local/bin/brseq b/stow/.local/bin/brseq
--- a/stow/.local/bin/brseq
+++ b/stow/.local/bin/brseq
@@ -2,32 +2,30 @@
 
 set -eu
 
-# Default options:
-format="%d/%b (%n of %N)%e"
+format=%d/%b_%n%e
 start_num=1
 increment=1
-width=1
 
-me=${0##*/}
+name=${0##*/}
 usage="Rename files as a sequence of numbers.
 
-Usage: $me [OPTIONS] FILE...
+Usage:
+    $name [OPTIONS] FILE...
 
 Options:
-    -h           show this help message
+    -n           dry-run (make no changes)
     -w           equalize width by padding with leading zeroes
-    -n           show the renamed files without actually renaming them
-    -s NUMBER    change start number (default: 1)
-    -i NUMBER    change increment (default: 1)
-    -W NUMBER    set the width of each number to NUMBER characters with leading zeroes
-    -f FORMAT    format file basename before extension (default: '$format')
+    -W NUMBER    pad each number to an exact width with leading zeroes
+    -s NUMBER    starting number (default: $start_num)
+    -i NUMBER    increment (default: $increment)
+    -f FORMAT    file path format (default: $format)
 
-When specifying FORMAT, it can include some placeholders:
-    %N           the total number of files
-    %n           the number of FILE
-    %d           the directory of FILE
-    %b           the basename of FILE
-    %e           the extension of FILE
+The following placeholders are recognized in FORMAT:
+    %n           number of FILE (required)
+    %N           total number of files
+    %d           directory of FILE
+    %b           basename of FILE
+    %e           extension of FILE
 "
 
 usage() {
@@ -36,51 +34,49 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
 declare -a seq_options
 
-unset OPTIND OPTARG
-while getopts ":hf:s:i:W:wn" option; do
+while getopts ":f:s:i:W:wnh" option; do
     case $option in
     f) format=$OPTARG ;;
     s) start_num=$OPTARG ;;
     i) increment=$OPTARG ;;
     W) width=$OPTARG ;;
     w) seq_options+=(-w) ;;
-    n) noop=1 ;;
+    n) dry_run=1 ;;
     h) usage ;;
-    *) die "invalid option: $OPTARG" ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
-unset option OPTIND OPTARG
 
 if [[ $format != *%n* ]]; then
-    die "format does not contain '%n'"
+    die "Format does not contain '%n'"
 fi
 
-if [[ $width == *[!0-9]* ]]; then
-    die "width must be a positive integer"
+if [[ -v width && $width == *[!0-9]* ]]; then
+    die "Width must be a positive integer"
 fi
 
 if [[ $start_num == *[!0-9]* ]]; then
-    die "start number must be a positive integer"
+    die "Start number must be a positive integer"
 fi
 
 if [[ $increment == *[!0-9]* ]]; then
-    die "increment must be a positive integer"
+    die "Increment must be a positive integer"
 fi
 
 end_num=$((start_num + $# - 1))
 
 format=${format/\%N/$#}
 
-readarray -t nums < <(seq "${seq_options[@]}" "$start_num" "$increment" "$end_num")
-
-for num in "${nums[@]}"; do
-    ((width > 1)) && num=$(printf "%0${width}d" "$num")
+while IFS= read -r -d $'\n' num; do
+    if [[ -v width ]]; then
+        num=$(printf "%0${width}d" "$num")
+    fi
 
     src=$1
     shift
@@ -95,9 +91,9 @@ for num in "${nums[@]}"; do
     dst=${dst/\%b/$base}
     dst=${dst/\%e/$ext}
 
-    if [[ ! -v noop ]]; then
+    if [[ ! -v dry_run ]]; then
         mv -i -T "$src" "$dst"
     fi
 
     echo "$dst"
-done
+done < <(seq "${seq_options[@]}" "$start_num" "$increment" "$end_num")
diff --git a/stow/.local/bin/queue b/stow/.local/bin/queue
--- a/stow/.local/bin/queue
+++ b/stow/.local/bin/queue
@@ -2,20 +2,23 @@
 
 set -eu
 
-me=${0##*/}
+name=${0##*/}
 usage="Safely manage a queue of items.
 
-Usage: $me [-h] [-lpc] [-a ITEM] FILE
-
-Options:
-    -h         show this help message
-    -a ITEM    add ITEM to queue
-    -l         list items in queue (this is the default)
-    -p         pop the next item and print it
-    -c         clear the queue
+Usage:
+    $name FILE [ACTION]
 
 Arguments:
-    FILE       use FILE as queue storage
+    FILE      file in which to store queued items
+    ACTION    action to perform against queue file
+
+Actions:
+    list      list items in the queue (default)
+    add       add items from stdin to queue
+    pop       remove next item from queue and print it
+    clear     remove all items from queue
+
+Items are popped from the top and added to the bottom.
 "
 
 usage() {
@@ -24,73 +27,65 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
-unset OPTIND OPTARG
-while getopts ":hplca:" option; do
+while getopts ":h" option; do
     case $option in
-    p) action="pop" ;;
-    l) action="list" ;;
-    c) action="clear" ;;
-    a)
-        action="add"
-        item=$OPTARG
-        ;;
     h) usage ;;
-    *) die "invalid option: $OPTARG" ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
-unset option OPTIND OPTARG
 
-queue=${1:?missing queue file}
+if [[ ! -v 1 ]]; then
+    die "Missing queue file"
+fi
+
+queue=$1
+action=${2:-list}
+
+case $action in
+list | add | pop | clear | hold) ;;
+*) die "Invalid action '$action'" ;;
+esac
 
 # Ensure this invocation has exclusive access to the queue file.
 # If it doesn't, wait until it does.
 
-if [[ "${FLOCKER:-}" != "$0" ]]; then
-    if [[ -z $queue ]]; then
-        die "no queue file provided"
-    fi
-
-    export FLOCKER=$0
-    export QUEUE=$queue
-    export ACTION=${action:-list}
-    export ITEM=${item:-}
-
-    exec flock "$queue" "$0" "$@"
+if [[ ${FLOCKER:-} != "$0" ]]; then
+    FLOCKER=$0 exec flock "$queue" "$0" "$queue" "$action"
 fi
 
 unset FLOCKER
 
-queue_list() {
-    grep -v -E "$@" '^\s*(#|$)' "$QUEUE"
+do_list() {
+    grep -v -E "$@" '^\s*(#|$)' "$queue"
 }
 
-queue_add() {
-    echo "$ITEM" >>"$QUEUE"
+do_add() {
+    cat >>"$queue"
 }
 
-queue_pop() {
+do_pop() {
     # Get the first line in the queue that isn't blank or commented out.
     # The line number is included so that it can be referenced directly with sed.
-    next=$(queue_list -m1 -n)
+    next=$(do_list -n -m1 "$@")
 
-    # As soon as the queue is empty, the grep command will fail and this script will
-    # exit with a non-zero status.
+    # As soon as the queue is empty, the grep command will fail and this script
+    # will exit with a non-zero status.
 
     line_num=${next%%:*}
     line=${next#*:}
 
     # Comment out the line that was just retrieved.
-    sed -E -i "${line_num}s/^\s*/# /" "$QUEUE"
+    sed -E -i "${line_num}s/^\s*/# /" "$queue"
 
     echo "$line"
 }
 
-queue_clear() {
-    sed -E -i "/^\s*[^#]/s/^\s*/# /" "$QUEUE"
+do_clear() {
+    sed -E -i "/^\s*[^#]/s/^\s*/# /" "$queue"
 }
 
-queue_"$ACTION"
+do_"$action"
diff --git a/stow/.local/bin/yank b/stow/.local/bin/yank
--- a/stow/.local/bin/yank
+++ b/stow/.local/bin/yank
@@ -1,22 +1,37 @@
 #!/usr/bin/env bash
 
 set -eu
+shopt -s nullglob
 
-me=${0##*/}
-usage="Yank file paths in order to operate on them in bulk.
+cache_dir=${XDG_CACHE_HOME:-$HOME/.cache}/yank
 
-Usage: $me [-h] [-alc] PATH...
+name=${0##*/}
+usage="Move text around using file-based registers.
+
+Usage:
+    $name [OPTIONS] ACTION
 
 Options:
-    -h    show this help message
-    -a    append paths
-    -l    list paths
-    -c    clear paths
+    -R              perform action on all existing registers
+    -r NAME         perform action on register (can use multiple times)
 
-The default action is to set the paths.
+    -C DIRECTORY    directory in which to store registers
+                    (default: $cache_dir)
+
+Arguments:
+    ACTION          perform action on lines of a register
+
+Actions:
+    list            print register names to stdout
+    set             set register contents from stdin
+    add             add lines from stdin to register
+    edit            open register in editor
+    print           print register to stdout
+    clear           clear register contents
+
+If no register is specified, it defaults to 'default'.
+When operating on all registers with -R, 'default' will be included.
 "
-
-paths=${XDG_CACHE_HOME:-$HOME/.cache}/yank/paths
 
 usage() {
     echo "$usage" >&2
@@ -24,39 +39,73 @@ usage() {
 }
 
 die() {
-    echo "$me: $*" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
 do_add() {
-    mkdir -p "$(dirname "$paths")"
-    realpath "$@" >>"$paths"
+    mkdir -p "$cache_dir"
+    tee -a "${register_files[@]}" >/dev/null
 }
 
 do_set() {
     do_clear
-    do_add "$@"
+    do_add
+}
+
+do_edit() {
+    exec "${VISUAL:-$EDITOR}" "${register_files[@]}"
 }
 
 do_list() {
-    [[ -f $paths ]] && cat "$paths"
+    if [[ -d $cache_dir ]]; then
+        find "$cache_dir" -type f -printf "%f\n"
+    fi
+}
+
+do_print() {
+    local register_file
+    for register_file in "${register_files[@]}"; do
+        if [[ -r $register_file ]]; then
+            cat "$register_file"
+        fi
+    done
 }
 
 do_clear() {
-    rm -f "$paths"
+    rm -f "${register_files[@]}"
 }
 
-action="set"
-unset OPTIND OPTARG
-while getopts ":halc" option; do
+declare -A register_files_seen=()
+
+while getopts ":r:RC:h" option; do
     case $option in
-    a) action="add" ;;
-    l) action="list" ;;
-    c) action="clear" ;;
+    R)
+        for register_file in "$cache_dir"/default "$cache_dir"/*; do
+            register_files_seen[$register_file]=1
+        done
+        ;;
+    r)
+        register_file=$cache_dir/$OPTARG
+        register_files_seen[$register_file]=1
+        ;;
+    C) cache_dir=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option: $OPTARG" ;;
+    *) die "Invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
-unset option OPTIND OPTARG
 
-do_"$action" "$@"
+register_files=("${!register_files_seen[@]}")
+
+if ((${#register_files[@]} == 0)); then
+    register_files=("$cache_dir"/default)
+fi
+
+action=${1:-set}
+
+case $action in
+add | set | edit | list | print | clear) ;;
+*) die "Invalid action '$action'" ;;
+esac
+
+do_"$action"
