Tinkering

diff --git a/stow/.local/bin/download b/stow/.local/bin/download
--- a/stow/.local/bin/download
+++ b/stow/.local/bin/download
@@ -3,25 +3,16 @@
 set -e
 
 me=${0##*/}
+
 usage="Manage file downloads.
-Usage: $me [options] [URI...]
-
-Options:
-    -h         Display help.
-    -H HOOK    Run hook named HOOK
-
-Examples:
-    Download file (or add to existing session):
-        $me https://domain.net/path/to/file
-
-    Resume download session (if canceled):
-        $me
+Usage: $me -h      # show this help message
+       $me URI...  # add URI(s) to session
+       $me         # resume session
 "
 
-target=$1
 token=$USER@$HOSTNAME
 
-if which xdg-user-dir &>/dev/null; then
+if has xdg-user-dir; then
     dest=$(xdg-user-dir DOWNLOAD)
 else
     dest=$HOME/Downloads
@@ -29,6 +20,11 @@ fi
 
 data_dir=${XDG_DATA_HOME:-$HOME/.local/share}/aria2
 session=$data_dir/session
+
+die() {
+    echo "$me: $*" >&2
+    exit 1
+}
 
 add_uris() {
     local target=${1:?missing download target}
@@ -70,14 +66,13 @@ unset OPTIND concurrent
 while getopts ":hH:j:" option; do
     case $option in
     j) concurrent=$OPTARG ;;
+
     h)
         echo "$usage" >&2
         exit 0
         ;;
-    *)
-        echo "$usage" >&2
-        exit 1
-        ;;
+
+    *) die "invalid option '$option'" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/stow/.local/bin/queue b/stow/.local/bin/queue
--- a/stow/.local/bin/queue
+++ b/stow/.local/bin/queue
@@ -3,16 +3,20 @@
 set -e
 
 me=${0##*/}
-usage="Safely manage a queue of items.
-Usage: $me [options]
 
-Options:
-    -h             Display help.
-    -f FILENAME    Use FILENAME as queue file.
-    -a ITEM        Add ITEM to queue.
-    -l             List items in the queue (this is the default).
-    -p             Pop the next item from the queue and echo it.
-    -c             Clear the queue."
+usage="Safely manage a queue of items.
+Usage: $me -h       # show this help message
+       $me -f FILE  # use FILE as queue file
+       $me -a ITEM  # add ITEM to queue
+       $me -l       # list items in queue (this is the default)
+       $me -p       # pop the next item and print it
+       $me -c       # clear the queue
+"
+
+die() {
+    echo "$me: $*" >&2
+    exit 1
+}
 
 action="list"
 unset OPTIND queue item
@@ -26,14 +30,13 @@ while getopts ":hf:a:lpc" option; do
     p) action="pop" ;;
     l) action="list" ;;
     c) action="clear" ;;
+
     h)
         echo "$usage" >&2
         exit 0
         ;;
-    *)
-        echo "$usage" >&2
-        exit 1
-        ;;
+
+    *) die "invalid option '$option'" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -41,10 +44,7 @@ done && shift $((OPTIND - 1))
 # If it doesn't, wait until it does.
 
 if [[ "$FLOCKER" != "$0" ]]; then
-    if [[ ! $queue ]]; then
-        echo "ERROR: no queue file provided" >&2
-        exit 1
-    fi
+    [[ $queue ]] || die "no queue file provided"
 
     export FLOCKER=$0
     export QUEUE=$queue
@@ -57,10 +57,7 @@ unset FLOCKER
 
 require() {
     for name in "$@"; do
-        if [[ ! ${!name} ]]; then
-            echo "$name is not set" >&2
-            exit 1
-        fi
+        [[ ${!name} ]] || die "$name is not set"
     done
 }
 
@@ -71,12 +68,6 @@ queue_list() {
 
 queue_add() {
     require ITEM QUEUE
-
-    if [[ ! $ITEM ]]; then
-        echo "ERROR: no item provided" >&2
-        exit 1
-    fi
-
     echo "$ITEM" >>"$QUEUE"
 }
 
@@ -105,5 +96,4 @@ queue_clear() {
 }
 
 require ACTION
-
 queue_$ACTION
diff --git a/stow/.local/bin/snip b/stow/.local/bin/snip
--- a/stow/.local/bin/snip
+++ b/stow/.local/bin/snip
@@ -3,14 +3,22 @@
 set -e
 
 me=${0##*/}
+
 usage="Interact with text snippets.
-Usage: $me [-h] [-l] [-p|e|c|s|t name]"
+Usage: $me -h       # show this help message
+       $me -l       # list snippets
+       $me -p NAME  # print snippet to stdout
+       $me -e NAME  # edit snippet in preferred editor
+       $me -c NAME  # copy snippet to clipboard
+       $me -s NAME  # save clipboard to snippet
+       $me -t NAME  # type snippet in active window
+"
 
 config_dir=${XDG_CONFIG_HOME:-$HOME/.config}/snip
 snippets=$config_dir/snippets
 
 die() {
-    echo "$*" >&2
+    echo "$me: $*" >&2
     exit 1
 }
 
@@ -32,9 +40,7 @@ get_snippet_file() {
 
 list_snippets() {
     if [[ -d $snippets ]]; then
-        find "$snippets" -type f | while read -r file; do
-            basename "$file"
-        done
+        find "$snippets" -type f -exec basename {} \;
     fi
 }
 
@@ -53,7 +59,7 @@ edit_snippet() {
 
     mkdir -p "$snippets"
 
-    exec "${VISUAL[@]}" "$file"
+    exec visual "$file"
 }
 
 copy_snippet() {
@@ -98,13 +104,12 @@ while getopts ":hlp:e:c:s:t:" option; do
     c) copy_snippet "$OPTARG" ;;
     s) save_snippet "$OPTARG" ;;
     t) type_snippet "$OPTARG" ;;
+
     h)
         echo "$usage" >&2
         exit 0
         ;;
-    *)
-        echo "$usage" >&2
-        exit 1
-        ;;
+
+    *) die "invalid option '$option'" ;;
     esac
 done && shift $((OPTIND - 1))
diff --git a/stow/.local/bin/yank b/stow/.local/bin/yank
--- a/stow/.local/bin/yank
+++ b/stow/.local/bin/yank
@@ -3,16 +3,21 @@
 set -e
 
 me=${0##*/}
+
 usage="Yank file paths in order to operate on them in bulk.
 Usage: $me -h|--help                 # show this help message
        $me -l|--list                 # list paths
        $me [-a|--add] path...        # set (or append with -a) paths
-       $me -x|--exec command arg...  # execute command against paths (see \`man xargs\`)"
+       $me -x|--exec command arg...  # execute command against paths (see \`man xargs\`)
+"
 
 cache=${XDG_CACHE_HOME:-$HOME/.cache}/yank
-mkdir -p "$cache"
-
 paths=$cache/paths
+
+die() {
+    echo "$me: $*" >&2
+    exit 1
+}
 
 do_list() {
     [[ -f $paths ]] && cat "$paths"
@@ -24,6 +29,7 @@ do_set() {
 }
 
 do_add() {
+    mkdir -p "$(dirname "$paths")"
     realpath "$@" >>"$paths"
 }
 
@@ -43,31 +49,23 @@ while true; do
     pos=$1
     shift
 
-    [[ $pos ]] || break
-
     case "$pos" in
-    -l | --list)
-        action="list"
-        ;;
-    -a | --add)
-        action="add"
-        ;;
-    -c | --clear)
-        action="clear"
-        ;;
+    -l | --list) action="list" ;;
+    -a | --add) action="add" ;;
+    -c | --clear) action="clear" ;;
+
+    # If present, emaining arguments should go to exec
     -x | --exec)
         do_exec "$@"
         exit
         ;;
+
     -h | --help)
         echo "$usage" >&2
-        exit 0
+        exit
         ;;
-    -*)
-        echo "$me: invalid option '$pos'" >&2
-        echo "$usage" >&2
-        exit 1
-        ;;
+
+    -*) die "invalid option '$pos'" ;;
     esac
 done
 
