Add ghc installer. Fix direnv for bash

diff --git a/stow/.local/bin/vim-stdin b/stow/.local/bin/vim-stdin
--- a/stow/.local/bin/vim-stdin
+++ b/stow/.local/bin/vim-stdin
@@ -7,7 +7,7 @@ set -eu
 readarray -t paths
 
 if ((${#paths[@]} == 0)); then
-    echo "${0##*/}: nothing to edit" >&2
+    echo "ERROR: nothing to edit" >&2
     exit 1
 fi
 
