Clean up stdout/stderr usage

diff --git a/stow/.local/bin/vim-stdin b/stow/.local/bin/vim-stdin
--- a/stow/.local/bin/vim-stdin
+++ b/stow/.local/bin/vim-stdin
@@ -8,7 +8,7 @@ set -eu
 readarray -t paths
 
 if ((${#paths[@]} == 0)); then
-    echo "ERROR: nothing to edit" >&2
+    echo "ERROR: Nothing to edit" >&2
     exit 1
 fi
 
