make error messages more consistent

diff --git a/files/home/.local/bin/br b/files/home/.local/bin/br
--- a/files/home/.local/bin/br
+++ b/files/home/.local/bin/br
@@ -18,8 +18,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 mkbr_options=()
@@ -28,7 +28,7 @@ while getopts ":fh" option; do
     case $option in
     f) mkbr_options+=(-f) ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/brhash b/files/home/.local/bin/brhash
--- a/files/home/.local/bin/brhash
+++ b/files/home/.local/bin/brhash
@@ -22,8 +22,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 extname() {
@@ -36,12 +36,12 @@ while getopts ":fh" option; do
     case $option in
     f) mkbr_options+=(-f) ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
 if [[ ! -v 1 ]]; then
-    die "no algorithm provided"
+    die "missing algorithm"
 fi
 
 for possible_algorithm in "${algorithms[@]}"; do
@@ -53,7 +53,7 @@ for possible_algorithm in "${algorithms[@]}"; do
 done
 
 if [[ ! -v algorithm ]]; then
-    die "invalid digest algorithm"
+    die "invalid digest algorithm -- $1"
 fi
 
 temp_dir=$(mktemp -d -t "${me}.XXXXXXXXXX")
diff --git a/files/home/.local/bin/brseq b/files/home/.local/bin/brseq
--- a/files/home/.local/bin/brseq
+++ b/files/home/.local/bin/brseq
@@ -34,8 +34,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 extname() {
@@ -55,12 +55,12 @@ while getopts ":F:s:i:W:wfh" option; do
     w) auto_width=1 ;;
     f) mkbr_options+=(-f) ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
 if [[ $format != *%n* ]]; then
-    die "format does not contain '%n'"
+    die "format must contain '%n'"
 fi
 
 if [[ -v width && $width == *[!0-9]* ]]; then
diff --git a/files/home/.local/bin/mkbr b/files/home/.local/bin/mkbr
--- a/files/home/.local/bin/mkbr
+++ b/files/home/.local/bin/mkbr
@@ -31,8 +31,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 get_num_lines() {
@@ -45,7 +45,7 @@ while getopts ":fh" option; do
     case $option in
     f) mv_option=f ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/on-change b/files/home/.local/bin/on-change
--- a/files/home/.local/bin/on-change
+++ b/files/home/.local/bin/on-change
@@ -20,8 +20,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 directories=()
@@ -30,7 +30,7 @@ while getopts ":d:h" option; do
     case $option in
     d) directories+=("$OPTARG") ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift "$((OPTIND - 1))"
 
diff --git a/files/home/.local/bin/queue b/files/home/.local/bin/queue
--- a/files/home/.local/bin/queue
+++ b/files/home/.local/bin/queue
@@ -27,27 +27,23 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 while getopts ":h" option; do
     case $option in
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
-
-if [[ ! -v 1 ]]; then
-    die "missing queue file"
-fi
 
 queue=${1:?missing queue file}
 action=${2:-list}
 
 case $action in
 list | add | pop | clear | hold) ;;
-*) die "invalid action '$action'" ;;
+*) die "invalid action -- $action" ;;
 esac
 
 # Ensure this invocation has exclusive access to the queue file.
diff --git a/files/home/.local/bin/snip b/files/home/.local/bin/snip
--- a/files/home/.local/bin/snip
+++ b/files/home/.local/bin/snip
@@ -33,8 +33,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 snippet_file() {
@@ -46,7 +46,7 @@ snippet_file_required() {
     file=$(snippet_file "$1")
 
     if [[ ! -f $file ]]; then
-        die "snippet file does not exist: $file"
+        die "snippet file does not exist -- $file"
     fi
 
     printf "%s\n" "$file"
@@ -89,7 +89,7 @@ while getopts ":C:h" option; do
     case $option in
     C) config_dir=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -98,7 +98,7 @@ shift
 
 case $action in
 list | path | read | write | edit | delete) ;;
-*) die "invalid action '$action'" ;;
+*) die "invalid action -- $action" ;;
 esac
 
 if [[ $action == list ]]; then
diff --git a/files/home/.local/bin/yank b/files/home/.local/bin/yank
--- a/files/home/.local/bin/yank
+++ b/files/home/.local/bin/yank
@@ -39,8 +39,8 @@ usage() {
 }
 
 die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
-    exit 1
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
+    exit "${2:-1}"
 }
 
 list_register_files() {
@@ -91,7 +91,7 @@ while getopts ":aC:h" option; do
     a) select_all=1 ;;
     C) cache_dir=$OPTARG ;;
     h) usage ;;
-    *) die "invalid option '$OPTARG'" ;;
+    *) die "invalid option -- $OPTARG" ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -110,7 +110,7 @@ fi
 
 case $action in
 add | set | edit | list | print | clear) ;;
-*) die "invalid action '$action'" ;;
+*) die "invalid action -- $action" ;;
 esac
 
 do_"$action"
