Tinkering

diff --git a/files/home/.local/bin/br b/files/home/.local/bin/br
--- a/files/home/.local/bin/br
+++ b/files/home/.local/bin/br
@@ -1,38 +1,32 @@
 #!/usr/bin/env bash
 
-set -eu
+set -euo pipefail
 
-me=${0##*/}
 usage="Rename files using your preferred editor.
 
 Usage:
-    $me [OPTIONS] FILE...
+    ${0##*/} [OPTIONS] FILE...
 
 Options:
-    -f    use -f instead of -i for generated mv commands
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+    -f    use -f instead of -i for generated mv commands"
 
 mkbr_options=()
 
 while getopts ":fh" option; do
     case $option in
     f) mkbr_options+=(-f) ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
-temp_dir=$(mktemp -d -t "${me}.XXXXXXXXXX")
+temp_dir=$(mktemp -d -t "${0##*/}".XXXXXXXXXX)
 printf -v cleanup "rm -r %q" "$temp_dir"
 trap '$cleanup' EXIT
 
@@ -42,6 +36,12 @@ dst_list=$temp_dir/dst
 if (($# == 0)); then
     cat >"$src_list"
 else
+    for path in "$@"; do
+        if [[ $path == *$'\n'* ]]; then
+            printf "Invalid path: %q (contains newline)\n" "$path" >&2
+            exit 1
+        fi
+    done
     printf "%s\n" "$@" >"$src_list"
 fi
 
diff --git a/files/home/.local/bin/brhash b/files/home/.local/bin/brhash
--- a/files/home/.local/bin/brhash
+++ b/files/home/.local/bin/brhash
@@ -1,30 +1,18 @@
 #!/usr/bin/env bash
 
-set -eu
+set -euo pipefail
 
 algorithms=(md5 sha{1,224,256,384,512} b2)
 
-me=${0##*/}
 usage="Rename files to hashes based on contents.
 
 Usage:
-    $me [OPTIONS] ALGORITHM FILE...
+    ${0##*/} [OPTIONS] ALGORITHM FILE...
 
 Options:
     -f    use -f instead of -i in the generated mv commands
 
-Where ALGORITHM is one of: ${algorithms[*]}
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+Where ALGORITHM is one of: ${algorithms[*]}"
 
 extname() {
     awk 'match($0, /(\.[[:alnum:]]+)+$/) { print substr($0, RSTART, RLENGTH) }' <<<"$1"
@@ -35,28 +23,33 @@ mkbr_options=()
 while getopts ":fh" option; do
     case $option in
     f) mkbr_options+=(-f) ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
 if [[ ! -v 1 ]]; then
-    die "missing algorithm"
+    printf "The first argument must be a valid algorithm\n" >&2
+    exit 1
 fi
 
-for possible_algorithm in "${algorithms[@]}"; do
-    if [[ $possible_algorithm == "$1" ]]; then
-        algorithm=$possible_algorithm
-        shift
-        break
-    fi
-done
-
-if [[ ! -v algorithm ]]; then
-    die "invalid digest algorithm -- $1"
+if ! printf "%s\n" "${algorithms[@]}" | grep -q "^$1$"; then
+    printf "Invalid algorithm: %s\n" "$1" >&2
+    printf "Recognized algorithms: %s\n" "${algorithms[*]}" >&2
+    exit 1
 fi
 
-temp_dir=$(mktemp -d -t "${me}.XXXXXXXXXX")
+algorithm=$1
+
+shift
+
+temp_dir=$(mktemp -d -t "${0##*/}".XXXXXXXXXX)
 printf -v cleanup "rm -r %q" "$temp_dir"
 trap '$cleanup' EXIT
 
@@ -66,12 +59,16 @@ dst_list=$temp_dir/dst
 if (($# == 0)); then
     cat >"$src_list"
 else
+    for path in "$@"; do
+        if [[ $path == *$'\n'* ]]; then
+            printf "Invalid path: %q (contains newline)\n" "$path" >&2
+            exit 1
+        fi
+    done
     printf "%s\n" "$@" >"$src_list"
 fi
 
 while read -r src; do
-    [[ -f $src && -r $src ]] || continue
-
     dir=$(dirname "$src")
     ext=$(extname "$src")
     base=$("$algorithm"sum "$src" | awk '{print $1}')
diff --git a/files/home/.local/bin/brseq b/files/home/.local/bin/brseq
--- a/files/home/.local/bin/brseq
+++ b/files/home/.local/bin/brseq
@@ -1,16 +1,15 @@
 #!/usr/bin/env bash
 
-set -eu
+set -euo pipefail
 
 format=%d/%n%e
 start_num=1
 increment=1
 
-me=${0##*/}
 usage="Rename files as a sequence of numbers.
 
 Usage:
-    $me [OPTIONS] FILE...
+    ${0##*/} [OPTIONS] FILE...
 
 Options:
     -f           use -f instead of -i in the generated mv commands
@@ -25,18 +24,7 @@ The following placeholders are recognized in FORMAT:
     %N           total number of files
     %d           directory of FILE
     %b           basename of FILE
-    %e           extension of FILE
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+    %e           extension of FILE"
 
 extname() {
     awk 'match($0, /(\.[[:alnum:]]+)+$/) { print substr($0, RSTART, RLENGTH) }' <<<"$1"
@@ -54,28 +42,38 @@ while getopts ":F:s:i:W:wfh" option; do
     W) width=$OPTARG ;;
     w) auto_width=1 ;;
     f) mkbr_options+=(-f) ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
 if [[ $format != *%n* ]]; then
-    die "format must contain '%n'"
+    printf "Invalid format: %q (must contain %%n)\n" "$format" >&2
+    exit 1
 fi
 
 if [[ -v width && $width == *[!0-9]* ]]; then
-    die "width must be a positive integer"
+    printf "Invalid width: %s (must be a positive integer)\n" "$width">&2
+    exit 1
 fi
 
 if [[ $start_num == *[!0-9]* ]]; then
-    die "start number must be a positive integer"
+    printf "Invalid start number: %s (must be a positive integer)\n" "$start_num" >&2
+    exit 1
 fi
 
 if [[ $increment == *[!0-9]* ]]; then
-    die "increment must be a positive integer"
+    printf "Invalid increment: %s (must be a positive integer)\n" "$increment" >&2
+    exit 1
 fi
 
-temp_dir=$(mktemp -d -t "${me}.XXXXXXXXXX")
+temp_dir=$(mktemp -d -t "${0##*/}".XXXXXXXXXX)
 printf -v cleanup "rm -r %q" "$temp_dir"
 trap '$cleanup' EXIT
 
@@ -85,6 +83,12 @@ dst_list=$temp_dir/dst
 if (($# == 0)); then
     cat >"$src_list"
 else
+    for path in "$@"; do
+        if [[ $path == *$'\n'* ]]; then
+            printf "Invalid path: %q (contains newline)\n" "$path" >&2
+            exit 1
+        fi
+    done
     printf "%s\n" "$@" >"$src_list"
 fi
 
@@ -97,15 +101,12 @@ if ((auto_width)); then
     width=${#end_num}
 fi
 
-while read -r src; do
+while IFS= read -r src; do
     if [[ -v width ]]; then
-        printf -v num_padded "%0${width}d" "$num"
+        printf -v num_padded "%0*d" "$width" "$num"
     else
         num_padded=$num
     fi
-
-    src=$1
-    shift
 
     dir=$(dirname "$src")
     ext=$(extname "$src")
@@ -117,7 +118,7 @@ while read -r src; do
     dst=${dst/\%b/$base}
     dst=${dst/\%e/$ext}
 
-    printf "$dst\n" >>"$dst_list"
+    printf "%s\n" "$dst" >>"$dst_list"
 
     num=$((num + increment))
 done <"$src_list"
diff --git a/files/home/.local/bin/enable-deno b/files/home/.local/bin/enable-deno
--- a/files/home/.local/bin/enable-deno
+++ b/files/home/.local/bin/enable-deno
@@ -5,31 +5,29 @@
 
 set -euo pipefail
 
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+REPO_URL=https://github.com/denoland/deno
 
-REPO=denoland/deno
-
-releases_file=$(mktemp -t "${0##*/}.XXXXXXXXXX")
-printf -v cleanup "rm %q" "$releases_file"
+versions_file=$(mktemp -t "${0##*/}".XXXXXXXXXX)
+printf -v cleanup "rm %q" "$versions_file"
 trap '$cleanup' EXIT
 
-curl -sSL -o "$releases_file" \
-    "https://api.github.com/repos/$REPO/releases"
+git ls-remote --tags --refs "$REPO_URL" |
+    sed -n "s:^.*refs/tags/v\(\S*\).*$:\1:p" |
+    sort -r --version-sort >"$versions_file"
 
-if [[ -v 1 ]]; then
-    release_json=$(jq -er --arg version "$1" 'map(select(.tag_name == "v" + $version)) | first' "$releases_file") || die "version not found: $1"
+if [[ ! -v 1 ]]; then
+    version=$(grep -vi -m1 '[a-z]' "$versions_file")
+elif ! grep -q "^$1$" "$versions_file"; then
+    printf "Invalid version: %s\n" "$1" >&2
+    exit 1
 else
-    release_json=$(jq -r '.[0]' "$releases_file")
+    version=$1
 fi
 
-tag=$(jq -r '.tag_name' <<<"$release_json")
-version=${tag#v}
+tag=v$version
 
 prefix=${XDG_DATA_HOME:-$HOME/.local/share}/deno/$version
-archive=${XDG_CACHE_HOME:-$HOME/.cache}/deno/deno-$version.zip
+archive_file=${XDG_CACHE_HOME:-$HOME/.cache}/deno/deno-$version.zip
 
 kernel=$(uname --kernel-name)
 machine=$(uname --machine)
@@ -45,11 +43,11 @@ esac
 
 target=$machine-$kernel
 
-if [[ ! -f $archive ]]; then
-    printf "Downloading Deno v%s\n" "$version" >&2
-    mkdir -p "$(dirname "$archive")"
-    url=https://github.com/$REPO/releases/download/$tag/deno-$target.zip
-    curl -L --progress-bar -o "$archive" "$url" || die "unable to download archive -- $url"
+if [[ ! -f $archive_file ]]; then
+    archive_url=$REPO_URL/releases/download/$tag/deno-$target.zip
+    printf "Downloading Deno v%s: %s\n" "$version" "$archive_url"
+    mkdir -p "$(dirname "$archive_file")"
+    curl -L -o "$archive_file" "$archive_url"
 fi
 
 if [[ -d $prefix ]]; then
@@ -57,4 +55,4 @@ if [[ -d $prefix ]]; then
 fi
 
 mkdir -p "$prefix"/bin
-unzip -d "$prefix"/bin -o "$archive"
+unzip -d "$prefix"/bin -o "$archive_file"
diff --git a/files/home/.local/bin/enable-minecraft-fabric-server b/files/home/.local/bin/enable-minecraft-fabric-server
--- a/files/home/.local/bin/enable-minecraft-fabric-server
+++ b/files/home/.local/bin/enable-minecraft-fabric-server
@@ -3,13 +3,21 @@
 # Initialize a Fabric-enabled Mincraft server for the given version.
 # Usage: enable-minecraft-fabric-server [VERSION]
 
-set -eu
+set -euo pipefail
 
-latest_version() {
-    curl -sSL https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r .latest.release
-}
+version_file=$(mktemp -t "${0##*/}".XXXXXXXXXX)
+printf -v cleanup "rm %q" "$version_file"
+trap '$cleanup' EXIT
 
-version=${1:-$(latest_version)}
+curl -sSL -o "$version_file" https://launchermeta.mojang.com/mc/game/version_manifest.json
+
+version=${1:-$(jq -er .latest.release "$version_file")}
+
+if ! jq -er --arg version "$version" '.versions[] | select(.id == $version)' "$version_file" >/dev/null; then
+    printf "Invalid version: %s\n" "$version" >&2
+    exit 1
+fi
+
 prefix=${XDG_DATA_HOME:-$HOME/.local/share}/mincraft-fabric-server/$version
 
 if [[ -d $prefix ]]; then
@@ -19,11 +27,11 @@ fi
 mkdir -p "$prefix"
 cd "$prefix"
 
-installer_url=$(curl -sSL https://meta.fabricmc.net/v2/versions/installer | jq -r .[0].url)
-curl -L --progress-bar -o installer.jar "$installer_url"
+installer_url=$(curl -sSL https://meta.fabricmc.net/v2/versions/installer | jq -er .[0].url)
+curl -L -o installer.jar "$installer_url"
 java -jar installer.jar server -mcversion "$version" -downloadMinecraft
 
 mv server.jar vanilla.jar
-ln -sfvn fabric-server-launch.jar server.jar
+ln -vsfn fabric-server-launch.jar server.jar
 printf "serverJar=vanilla.jar\n" >fabric-server-launcher.properties
 printf "eula=true\n" >eula.txt
diff --git a/files/home/.local/bin/enable-minecraft-server b/files/home/.local/bin/enable-minecraft-server
--- a/files/home/.local/bin/enable-minecraft-server
+++ b/files/home/.local/bin/enable-minecraft-server
@@ -1,34 +1,34 @@
 #!/usr/bin/env bash
 
-# Download Minecraft server for the given version.
+# Initialize a Minecraft server for the given version.
 # Usage: enable-minecraft-server [VERSION]
 
-set -eu
+set -euo pipefail
 
-versions_file=$(mktemp -t "${0##*/}.XXXXXXXXXX")
+versions_file=$(mktemp -t "${0##*/}".XXXXXXXXXX)
 printf -v cleanup "rm %q" "$versions_file"
 trap '$cleanup' EXIT
 
 curl -sSL -o "$versions_file" https://launchermeta.mojang.com/mc/game/version_manifest.json
 
-version=${1:-$(jq -r ".latest.release" "$versions_file")}
+version=${1:-$(jq -er .latest.release "$versions_file")}
+
+if ! version_json=$(jq -er --arg version "$version" '.versions | map(select(.id == $version)) | first' "$versions_file"); then
+    printf "Invalid version: %s\n" "$version" >&2
+    exit 1
+fi
+
 prefix=${XDG_DATA_HOME:-$HOME/.local/share}/mincraft-server/$version
 
 if [[ -d $prefix ]]; then
     exit 0
 fi
 
-release_json=$(
-    jq -r --arg version "$version" \
-        '.versions | map(select(.id == $version)) | first' \
-        "$versions_file"
-)
-
-downloads_url=$(jq -r ".url" <<<"$release_json")
-downloads_json=$(curl -sSL "$downloads_url" | jq -r ".downloads")
+downloads_url=$(jq -er .url <<<"$version_json")
+downloads_json=$(curl -sSL "$downloads_url" | jq -er .downloads)
 
 mkdir -p "$prefix"
 cd "$prefix"
 
-curl -L --progress-bar -o server.jar "$(jq -r ".server.url" <<<"$downloads_json")"
+curl -L -o server.jar "$(jq -er .server.url <<<"$downloads_json")"
 printf "eula=true\n" >eula.txt
diff --git a/files/home/.local/bin/enable-minecraft-spigot-server b/files/home/.local/bin/enable-minecraft-spigot-server
--- a/files/home/.local/bin/enable-minecraft-spigot-server
+++ b/files/home/.local/bin/enable-minecraft-spigot-server
@@ -1,8 +1,23 @@
 #!/usr/bin/env bash
 
-set -eu
+# Initialize a Spigot-enabled Mincraft server for the given version.
+# Usage: enable-minecraft-spigot-server [VERSION]
 
-version=${1:-latest}
+set -euo pipefail
+
+versions_file=$(mktemp -t "${0##*/}".XXXXXXXXXX)
+printf -v cleanup "rm %q" "$versions_file"
+trap '$cleanup' EXIT
+
+curl -sSL -o "$versions_file" https://launchermeta.mojang.com/mc/game/version_manifest.json
+
+version=${1:-$(jq -er .latest.release "$versions_file")}
+
+if ! jq -er --arg version "$version" '.versions[] | select(.id == $version)' "$versions_file" >/dev/null; then
+    printf "Invalid version: %s\n" "$version" >&2
+    exit 1
+fi
+
 prefix=${XDG_DATA_HOME:-$HOME/.local/share}/mincraft-spigot-server/$version
 
 if [[ -d $prefix ]]; then
@@ -12,10 +27,9 @@ fi
 mkdir -p "$prefix"
 cd "$prefix"
 
-curl -LO --progress-bar \
-    https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
+curl -LO https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
 
 java -jar BuildTools.jar --rev "$version"
 output_file=$(grep -m1 "Saved as" BuildTools.log.txt | sed 's:^.* \.\/\(.*\)$:\1:')
-ln -sfvn "$output_file" server.jar
+ln -vsfn "$output_file" server.jar
 printf "eula=true\n" >eula.txt
diff --git a/files/home/.local/bin/enable-node b/files/home/.local/bin/enable-node
--- a/files/home/.local/bin/enable-node
+++ b/files/home/.local/bin/enable-node
@@ -5,54 +5,48 @@
 
 set -euo pipefail
 
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+REPO_URL=https://github.com/nodejs/node
 
-REPO=nodejs/node
-
-temp_dir=$(mktemp -d -t "${0##*/}.XXXXXXXXXX")
-printf -v cleanup "rm -r %q" "$temp_dir"
+versions_file=$(mktemp -t "${0##*/}".XXXXXXXXXX)
+printf -v cleanup "rm %q" "$versions_file"
 trap '$cleanup' EXIT
 
-releases_file=$temp_dir/releases.json
+git ls-remote --tags --refs "$REPO_URL" |
+    sed -n "s:^.*refs/tags/v\(\S*\).*$:\1:p" |
+    sort -r --version-sort >"$versions_file"
 
-curl -sSL -o "$releases_file" \
-    "https://api.github.com/repos/$REPO/releases"
-
-if [[ -v 1 ]]; then
-    release_json=$(jq -er --arg version "$1" 'map(select(.tag_name == "v" + $version)) | first' "$releases_file") || die "version not found: $1"
+if [[ ! -v 1 ]]; then
+    version=$(grep -vi -m1 '[a-z]' "$versions_file")
+elif ! grep -q "^$1$" "$versions_file"; then
+    printf "Invalid version: %s\n" "$1" >&2
+    exit 1
 else
-    release_json=$(jq -r '.[0]' "$releases_file")
+    version=$1
 fi
 
-tag=$(jq -r '.tag_name' <<<"$release_json")
-version=${tag#v}
+tag=v$version
 
 prefix=${XDG_DATA_HOME:-$HOME/.local/share}/node/$version
-archive=${XDG_CACHE_HOME:-$HOME/.cache}/node/node-$version.tar.xz
+archive_file=${XDG_CACHE_HOME:-$HOME/.cache}/node/node-$version.tar.xz
 
 kernel=$(uname --kernel-name)
 kernel=${kernel,,}
 machine=$(uname --machine)
 machine=${machine/#x86_/x}
 
-if [[ ! -f $archive ]]; then
-    printf "Downloading Node.js v%s\n" "$version" >&2
-    mkdir -p "$(dirname "$archive")"
-    url=https://nodejs.org/dist/$tag/node-$tag-$kernel-$machine.tar.xz
-    curl -L --progress-bar -o "$archive" "$url" || die "unable to download archive -- $url"
+if [[ ! -f $archive_file ]]; then
+    archive_url=https://nodejs.org/dist/$tag/node-$tag-$kernel-$machine.tar.xz
+    printf "Downloading Node.js v%s: %s\n" "$version" "$archive_url"
+    mkdir -p "$(dirname "$archive_file")"
+    curl -L -o "$archive_file" "$archive_url"
 fi
 
 if [[ -d $prefix ]]; then
     exit 0
 fi
 
-cd "$temp_dir"
-tar -xf "$archive"
-mkdir -p "$(dirname "$prefix")"
-mv "node-v${version}-${kernel}-${machine}" "$prefix"
+mkdir -p "$prefix"
+tar -vxf "$archive_file" -C "$prefix" --strip-components=1
 
 export PATH=$prefix/bin:$PATH
 
diff --git a/files/home/.local/bin/enable-python b/files/home/.local/bin/enable-python
--- a/files/home/.local/bin/enable-python
+++ b/files/home/.local/bin/enable-python
@@ -7,56 +7,54 @@ set -euo pipefail
 
 REPO_URL=https://github.com/python/cpython
 
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+temp_dir=$(mktemp -d -t "${0##*/}".XXXXXXXXXX)
+printf -v cleanup "rm -r %q" "$temp_dir"
+trap '$cleanup' EXIT
 
-versions() {
-    git ls-remote --tags --refs "$REPO_URL" |
-        sed -n "s:^.*refs/tags/v\(\S*\).*$:\1:p" |
-        sort --version-sort
-}
+versions_file=$temp_dir/versions
 
-latest_version() {
-    versions | grep -vi '[a-z][0-9]$' | tail -n1
-}
+git ls-remote --tags --refs "$REPO_URL" |
+    sed -n "s:^.*refs/tags/v\(\S*\).*$:\1:p" |
+    sort -r --version-sort >"$versions_file"
 
-version=${1:-$(latest_version)}
+if [[ ! -v 1 ]]; then
+    version=$(grep -vi -m1 '[a-z]' "$versions_file")
+elif ! grep -q "^$1$" "$versions_file"; then
+    printf "Invalid version: %s\n" "$1" >&2
+    exit 1
+else
+    version=$1
+fi
+
 prefix=${XDG_DATA_HOME:-$HOME/.local/share}/python/$version
-archive=${XDG_CACHE_HOME:-$HOME/.cache}/python/python-$version.tar.gz
+archive_file=${XDG_CACHE_HOME:-$HOME/.cache}/python/python-$version.tar.gz
 
-if [[ ! -f $archive ]]; then
-    printf "Downloading Python v%s\n" "$version" >&2
-    mkdir -p "$(dirname "$archive")"
-    url=$REPO_URL/archive/refs/tags/v${version}.tar.gz
-    curl -L --progress-bar -o "$archive" "$url" || die "unable to download archive -- $url"
+if [[ ! -f $archive_file ]]; then
+    archive_url=$REPO_URL/archive/refs/tags/v${version}.tar.gz
+    printf "Downloading Python v%s: %s\n" "$version" "$archive_url"
+    mkdir -p "$(dirname "$archive_file")"
+    curl -L -o "$archive_file" "$archive_url"
 fi
 
 if [[ -d $prefix ]]; then
     exit 0
 fi
 
-temp_dir=$(mktemp -d -t "${0##*/}.XXXXXXXXXX")
-printf -v cleanup "rm -r %q" "$temp_dir"
-trap '$cleanup' EXIT
-
 cd "$temp_dir"
-tar -xf "$archive"
-cd cpython-"$version"
+
+tar -xf "$archive_file" --strip-components=1
 
 ./configure --prefix="$prefix" --enable-optimizations
 make --jobs="$(nproc)" install
 
 export PATH=$prefix/bin:$PATH
 
-major=${version%%.*}
+major_version=${version%%.*}
 
 for name in pip idle pydoc python; do
-    ln -sfn "$prefix/bin/$name$major" "$prefix/bin/$name"
+    ln -vsfn "$prefix/bin/$name$major_version" "$prefix/bin/$name"
 done
-
-ln -sfn "$prefix/bin/python$major"-config "$prefix"/bin/python-config
+ln -vsfn "$prefix/bin/python$major_version"-config "$prefix"/bin/python-config
 
 pip install --upgrade pip
 
diff --git a/files/home/.local/bin/mkbr b/files/home/.local/bin/mkbr
--- a/files/home/.local/bin/mkbr
+++ b/files/home/.local/bin/mkbr
@@ -1,12 +1,11 @@
 #!/usr/bin/env bash
 
-set -eu
+set -euo pipefail
 
-me=${0##*/}
 usage="Generate, confirm, and execute a bulk rename script.
 
 Usage:
-    $me [OPTIONS] FROM_LIST TO_LIST
+    ${0##*/} [OPTIONS] FROM_LIST TO_LIST
 
 Options:
     -f           use -f instead of -i for generated mv commands
@@ -20,54 +19,56 @@ A script will be generated, opened in EDITOR for review, and executed with sh.
 It's expected that the path on a line in FROM_LIST corresponds with the path on
 the same line in TO_LIST.
 
+Even though it's considered valid for a file path to contain newlines, it's
+expected that they will not be present in any path of FROM_LIST or TO_LIST as
+newlines are used to separate paths in those lists.
+
 This command will error if the number of paths in each list does not match.
 
-It will exit silently if the lists are empty.
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
-
-get_num_lines() {
-    wc -l <"$1"
-}
+It will exit silently if the lists are empty."
 
 mv_option=i
 
 while getopts ":fh" option; do
     case $option in
     f) mv_option=f ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
-if (($# != 2)) || [[ ! -f $1 || ! -f $2 ]]; then
-    die "the first two parameters must be readable files"
+if (($# != 2)); then
+    printf "The first two parameters must be readable files\n" >&2
+    exit 1
 fi
+
+for file in "$@"; do
+    if [[ ! -f $file || ! -r $file ]]; then
+        printf "File does not exist or is not readable: %q\n" "$file" >&2
+        exit 1
+    fi
+done
 
 src_list=$1
 dst_list=$2
 
-src_num_lines=$(get_num_lines "$src_list")
-dst_num_lines=$(get_num_lines "$dst_list")
+src_num_lines=$(wc -l <"$src_list")
+dst_num_lines=$(wc -l <"$dst_list")
 
 if ((src_num_lines != dst_num_lines)); then
-    die "the number of paths does not match"
+    printf "The number of paths does not match: source=%d != destination=%d\n" "$src_num_lines" "$dst_num_lines" >&2
+    exit 1
 fi
 
-if ((src_num_lines == 0)); then
-    exit 0
-fi
+((src_num_lines == 0)) && exit 0
 
-script=$(mktemp -t "${me}.XXXXXXXXXX")
+script=$(mktemp -t "${0##*/}".XXXXXXXXXX)
 printf -v cleanup "rm %q" "$script"
 trap '$cleanup' EXIT
 
@@ -77,8 +78,8 @@ cat >"$script" <<-EOF
 EOF
 
 has_changes=0
-tmpl_mkdir="mkdir -vp -- %q\n"
-tmpl_mv="mv -v$mv_option -- %q %q\n"
+tmpl_mkdir="mkdir -vp -- %q"
+tmpl_mv="mv -v$mv_option -- %q %q"
 
 declare -A seen_dirs
 
@@ -87,9 +88,7 @@ exec 3<"$dst_list"
 while read -r src; do
     read -r dst <&3
 
-    if [[ $src == "$dst" ]]; then
-        continue
-    fi
+    [[ $src == "$dst" ]] && continue
 
     has_changes=1
 
@@ -98,12 +97,12 @@ while read -r src; do
 
     if [[ $src_dir != "$dst_dir" && ! -v seen_dirs[$dst_dir] ]]; then
         if [[ ! -d $dst_dir ]]; then
-            printf "$tmpl_mkdir" "$dst_dir" >>"$script"
+            printf "$tmpl_mkdir\n" "$dst_dir" >>"$script"
         fi
         seen_dirs[$dst_dir]=1
     fi
 
-    printf "$tmpl_mv" "$src" "$dst" >>"$script"
+    printf "$tmpl_mv\n" "$src" "$dst" >>"$script"
 done <"$src_list"
 
 if ((has_changes)); then
diff --git a/files/home/.local/bin/queue b/files/home/.local/bin/queue
--- a/files/home/.local/bin/queue
+++ b/files/home/.local/bin/queue
@@ -1,12 +1,11 @@
 #!/usr/bin/env bash
 
-set -eu
+set -euo pipefail
 
-me=${0##*/}
 usage="Safely manage a queue of items.
 
 Usage:
-    $me FILE [ACTION]
+    ${0##*/} FILE [ACTION]
 
 Arguments:
     FILE      file in which to store queued items
@@ -18,32 +17,35 @@ Actions:
     pop       remove next item from queue and print it
     clear     remove all items from queue
 
-Items are popped from the top and added to the bottom.
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+Items are popped from the top and added to the bottom."
 
 while getopts ":h" option; do
     case $option in
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
-queue=${1:?missing queue file}
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be a queue file\n" >&2
+    exit 1
+fi
+
+queue=$1
 action=${2:-list}
 
 case $action in
-list | add | pop | clear | hold) ;;
-*) die "invalid action -- $action" ;;
+list | add | pop | clear) ;;
+*)
+    printf "Invalid action: %s\n" "$action" >&2
+    exit 1
+    ;;
 esac
 
 # Ensure this invocation has exclusive access to the queue file.
diff --git a/files/home/.local/bin/retry b/files/home/.local/bin/retry
--- a/files/home/.local/bin/retry
+++ b/files/home/.local/bin/retry
@@ -2,28 +2,16 @@
 
 # Adapted from: https://bbs.archlinux.org/viewtopic.php?pid=431568#p431568
 
-set -eu
+set -euo pipefail
 
-me=${0##*/}
 usage="Run a command repeatedly until it succeeds or runs out of retries.
 
 Usage:
-    $me [OPTIONS] COMMAND [ARGUMENT...]
+    ${0##*/} [OPTIONS] COMMAND [ARGUMENT...]
 
 Options:
     -n NUMBER    try to run COMMAND a maximum of NUMBER times
-    -d NUMBER    wait NUMBER seconds between each try
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
+    -d NUMBER    wait NUMBER seconds between each try"
 
 retries_remaining=-1
 delay=0
@@ -32,8 +20,14 @@ while getopts ":n:d:h" option; do
     case $option in
     n) retries_remaining=$OPTARG ;;
     d) delay=$OPTARG ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG"
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
@@ -43,12 +37,8 @@ while ((retries_remaining != 0)); do
     ((retries_remaining--))
 
     "$@"
-
     exit_code=$?
-
-    if ((exit_code == 0)); then
-        break
-    fi
+    ((exit_code == 0)) && break
 
     sleep "$delay"
 done
diff --git a/files/home/.local/bin/snip b/files/home/.local/bin/snip
--- a/files/home/.local/bin/snip
+++ b/files/home/.local/bin/snip
@@ -1,104 +1,103 @@
 #!/usr/bin/env bash
 
-set -eu
+set -euo pipefail
+shopt -s nullglob globstar
 
-config_dir=${XDG_CONFIG_HOME:-$HOME/.config}/snip
+data_dir=${XDG_DATA_HOME:-$HOME/.local/share}/snip
 
-me=${0##*/}
 usage="Manage text snippets.
 
 Usage:
-    $me [OPTIONS] ACTION [NAME]
+    ${0##*/} -h
+    ${0##*/} [OPTIONS] list
+    ${0##*/} [OPTIONS] path|read|write|append|edit|delete NAME
 
 Options:
-    -C DIRECTORY    directory in which to store snippets
-                    (default: $config_dir)
+    -D DIRECTORY    directory in which to store snippets
+                    default: ${data_dir@Q}
 
 Arguments:
     ACTION          perform action on snippet
     NAME            snippet on which to perform action
 
 Actions:
-    list            print snippet names to stdout
+    list            print all snippet names to stdout
     path            print snippet path to stdout
-    read            dump snippet to stdout
-    write           create snippet from stdin
-    edit            open snippet in editor
+    read            print snippet content to stdout
+    write           set snippet content from stdin
+    append          add to snippet content from stdin
     delete          delete snippet
-"
-
-usage() {
-    printf "%s\n" "$usage"
-    exit 0
-}
-
-die() {
-    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
-    exit "${2:-1}"
-}
-
-snippet_file() {
-    printf "%s/%s" "$config_dir" "${1:?missing snippet name}"
-}
-
-snippet_file_required() {
-    local file
-    file=$(snippet_file "$1")
-
-    if [[ ! -f $file ]]; then
-        die "snippet file does not exist -- $file"
-    fi
-
-    printf "%s\n" "$file"
-}
+    edit            open snippet in editor"
 
 do_list() {
-    if [[ -d $config_dir ]]; then
-        find "$config_dir" -type f -printf "%P\n"
-    fi
+    local path
+    for path in "$data_dir"/**; do
+        if [[ -f $path ]]; then
+            printf "%s\n" "${path#"$data_dir/"}"
+        fi
+    done
 }
 
 do_path() {
-    snippet_file "$1"
+    if [[ ! -f $1 ]]; then
+        return 1
+    fi
+    printf "%s" "$1"
+}
+
+do_append() {
+    mkdir -p "$(dirname "$1")"
+    cat >>"$1"
 }
 
 do_write() {
-    local file
-    file=$(snippet_file "$1")
-    mkdir -p "$(dirname "$file")"
-    cat >"$file"
+    rm -f "$1"
+    do_append "$1"
 }
 
 do_read() {
-    local file
-    file=$(snippet_file_required "$1")
-    cat "$file"
+    [[ -f $1 ]] || return 1
+    cat "$1"
 }
 
 do_edit() {
-    exec ${EDITOR:-vim} "$(snippet_file "$1")"
+    mkdir -p "$(dirname "$1")"
+    ${EDITOR:-vim} "$1"
 }
 
 do_delete() {
-    local file
-    file=$(snippet_file_required "$1")
-    rm -f "$file"
+    rm -v "$1"
 }
 
-while getopts ":C:h" option; do
+umask 077
+
+while getopts ":D:h" option; do
     case $option in
-    C) config_dir=$OPTARG ;;
-    h) usage ;;
-    *) die "invalid option -- $OPTARG" ;;
+    D) data_dir=$OPTARG ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG"
+        exit 1
+        ;;
     esac
 done && shift $((OPTIND - 1))
 
-action=${1:?missing action}
-shift
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be an action\n" >&2
+    exit 1
+fi
+
+action=$1
 
 case $action in
-list | path | read | write | edit | delete) ;;
-*) die "invalid action -- $action" ;;
+list | path | read | write | append | delete | edit) ;;
+*)
+    printf "Invalid action: %s\n" "$action" >&2
+    exit 1
+    ;;
 esac
 
 if [[ $action == list ]]; then
@@ -106,7 +105,23 @@ if [[ $action == list ]]; then
     exit 0
 fi
 
-snippet_name=${1:?missing snippet name}
-shift
+if [[ ! -v 2 ]]; then
+    printf "The second argument must be a snippet name\n" >&2
+    exit 1
+fi
 
-do_"$action" "$snippet_name"
+snippet=$data_dir/$2
+
+if [[ $snippet == *$'\n'* ]]; then
+    printf "Invalid snippet path: %q (contains newline)\n" "$snippet" >&2
+    exit 1
+fi
+
+do_"$action" "$snippet"
+
+# Remove any orphaned directory nesting.
+if [[ -d $data_dir ]]; then
+    case $action in
+    delete | edit) find "$data_dir/" -mindepth 1 -type d -empty -delete ;;
+    esac
+fi
diff --git a/files/home/.local/bin/throttle b/files/home/.local/bin/throttle
--- a/files/home/.local/bin/throttle
+++ b/files/home/.local/bin/throttle
@@ -3,23 +3,42 @@
 # Only allow given command to be run once during a given period of time.
 # Usage: throttle ID DELAY COMMAND [ARGUMENT...]
 
-set -eu
+set -euo pipefail
 
-id=${1:?missing command ID}
-delay=${2:?missing delay}
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be a command identifier\n" >&2
+    exit 1
+fi
+
+if [[ ! -v 2 ]]; then
+    printf "The second argument must be a delay specification\n" >&2
+    exit 1
+fi
+
+if [[ ! $2 =~ ^[0-9.]+(s|m|h|d)?$ ]]; then
+    printf "Invalid delay specification: %s\n" "$2" >&2
+    printf "See sleep(1) for more information" >&2
+    exit 1
+fi
+
+id=$1
+delay=$2
+
 shift 2
 
-me=${0##*/}
-lock_file=$XDG_RUNTIME_DIR/$me-$id.lock
-
-if [[ -e $lock_file ]]; then
-    exit 0
+if [[ ! -v 1 ]]; then
+    printf "The remaining arguments must be a command\n" >&2
+    exit 1
 fi
+
+lock_file=$XDG_RUNTIME_DIR/${0##*/}-$id.lock
+
+[[ -e $lock_file ]] && exit 0
 
 printf -v cleanup "rm %q" "$lock_file"
 trap '$cleanup' EXIT
 touch "$lock_file"
 
-"${@:?missing command}"
+"$@"
 
 sleep "$delay"
