Tinkering

diff --git a/files/home/.local/bin/br b/files/home/.local/bin/br
--- a/files/home/.local/bin/br
+++ b/files/home/.local/bin/br
@@ -18,7 +18,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -28,7 +28,7 @@ while getopts ":fh" option; do
     case $option in
     f) mkbr_options+=(-f) ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
diff --git a/files/home/.local/bin/brhash b/files/home/.local/bin/brhash
--- a/files/home/.local/bin/brhash
+++ b/files/home/.local/bin/brhash
@@ -22,7 +22,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -36,12 +36,12 @@ while getopts ":fh" option; do
     case $option in
     f) mkbr_options+=(-f) ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
 if [[ ! -v 1 ]]; then
-    die "No algorithm provided"
+    die "no algorithm provided"
 fi
 
 for possible_algorithm in "${algorithms[@]}"; do
@@ -53,7 +53,7 @@ for possible_algorithm in "${algorithms[@]}"; do
 done
 
 if [[ ! -v algorithm ]]; then
-    die "Invalid digest algorithm"
+    die "invalid digest algorithm"
 fi
 
 temp_dir=$(mktemp -d -t "${me}.XXXXXXXXXX")
diff --git a/files/home/.local/bin/brseq b/files/home/.local/bin/brseq
--- a/files/home/.local/bin/brseq
+++ b/files/home/.local/bin/brseq
@@ -34,7 +34,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -55,24 +55,24 @@ while getopts ":F:s:i:W:wfh" option; do
     w) auto_width=1 ;;
     f) mkbr_options+=(-f) ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
 if [[ $format != *%n* ]]; then
-    die "Format does not contain '%n'"
+    die "format does not contain '%n'"
 fi
 
 if [[ -v width && $width == *[!0-9]* ]]; then
-    die "Width must be a positive integer"
+    die "width must be a positive integer"
 fi
 
 if [[ $start_num == *[!0-9]* ]]; then
-    die "Start number must be a positive integer"
+    die "start number must be a positive integer"
 fi
 
 if [[ $increment == *[!0-9]* ]]; then
-    die "Increment must be a positive integer"
+    die "increment must be a positive integer"
 fi
 
 temp_dir=$(mktemp -d -t "${me}.XXXXXXXXXX")
diff --git a/files/home/.local/bin/mkbr b/files/home/.local/bin/mkbr
--- a/files/home/.local/bin/mkbr
+++ b/files/home/.local/bin/mkbr
@@ -31,12 +31,8 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
-}
-
-is_readable_file() {
-    [[ -f $1 && -r $1 ]]
 }
 
 get_num_lines() {
@@ -49,12 +45,12 @@ while getopts ":fh" option; do
     case $option in
     f) mv_option=f ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
-if (($# != 2)) || ! is_readable_file "$1" || ! is_readable_file "$2"; then
-    die "The first two parameters must be readable files"
+if (($# != 2)) || [[ ! -f $1 || ! -f $2 ]]; then
+    die "the first two parameters must be readable files"
 fi
 
 src_list=$1
@@ -64,7 +60,7 @@ src_num_lines=$(get_num_lines "$src_list")
 dst_num_lines=$(get_num_lines "$dst_list")
 
 if ((src_num_lines != dst_num_lines)); then
-    die "The number of paths does not match"
+    die "the number of paths does not match"
 fi
 
 if ((src_num_lines == 0)); then
diff --git a/files/home/.local/bin/on-change b/files/home/.local/bin/on-change
--- a/files/home/.local/bin/on-change
+++ b/files/home/.local/bin/on-change
@@ -20,7 +20,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -30,7 +30,7 @@ while getopts ":d:h" option; do
     case $option in
     d) directories+=("$OPTARG") ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift "$((OPTIND - 1))"
 
diff --git a/files/home/.local/bin/queue b/files/home/.local/bin/queue
--- a/files/home/.local/bin/queue
+++ b/files/home/.local/bin/queue
@@ -27,19 +27,19 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
 while getopts ":h" option; do
     case $option in
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
 if [[ ! -v 1 ]]; then
-    die "Missing queue file"
+    die "missing queue file"
 fi
 
 queue=${1:?Missing queue file}
@@ -47,7 +47,7 @@ action=${2:-list}
 
 case $action in
 list | add | pop | clear | hold) ;;
-*) die "Invalid action '$action'" ;;
+*) die "invalid action '$action'" ;;
 esac
 
 # Ensure this invocation has exclusive access to the queue file.
diff --git a/files/home/.local/bin/snip b/files/home/.local/bin/snip
--- a/files/home/.local/bin/snip
+++ b/files/home/.local/bin/snip
@@ -33,7 +33,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -46,7 +46,7 @@ snippet_file_required() {
     file=$(snippet_file "$1")
 
     if [[ ! -f $file ]]; then
-        die "Snippet '$file' does not exist"
+        die "snippet file does not exist: $file"
     fi
 
     printf "%s\n" "$file"
@@ -89,20 +89,16 @@ while getopts ":C:h" option; do
     case $option in
     C) config_dir=$OPTARG ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
-if [[ ! -v 1 ]]; then
-    die "Missing action"
-fi
-
-action=$1
+action=${1:?missing action}
 shift
 
 case $action in
 list | path | read | write | edit | delete) ;;
-*) die "Invalid action '$action'" ;;
+*) die "invalid action '$action'" ;;
 esac
 
 if [[ $action == list ]]; then
@@ -110,11 +106,7 @@ if [[ $action == list ]]; then
     exit 0
 fi
 
-if [[ ! -v 1 ]]; then
-    die "Missing snippet name"
-fi
-
-snippet_name=$1
+snippet_name=${1:?missing snippet name}
 shift
 
 do_"$action" "$snippet_name"
diff --git a/files/home/.local/bin/yank b/files/home/.local/bin/yank
--- a/files/home/.local/bin/yank
+++ b/files/home/.local/bin/yank
@@ -39,7 +39,7 @@ usage() {
 }
 
 die() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$*" >&2
     exit 1
 }
 
@@ -91,11 +91,11 @@ while getopts ":aC:h" option; do
     a) select_all=1 ;;
     C) cache_dir=$OPTARG ;;
     h) usage ;;
-    *) die "Invalid option '$OPTARG'" ;;
+    *) die "invalid option '$OPTARG'" ;;
     esac
 done && shift $((OPTIND - 1))
 
-action=$1
+action=${1:?missing action}
 shift
 
 if ((select_all)); then
@@ -110,7 +110,7 @@ fi
 
 case $action in
 add | set | edit | list | print | clear) ;;
-*) die "Invalid action '$action'" ;;
+*) die "invalid action '$action'" ;;
 esac
 
 do_"$action"
