Tinkering

diff --git a/files/home/.local/bin/brhash b/files/home/.local/bin/brhash
--- a/files/home/.local/bin/brhash
+++ b/files/home/.local/bin/brhash
@@ -35,18 +35,13 @@ while getopts ":fh" option; do
     esac
 done && shift $((OPTIND - 1))
 
-if [[ ! -v 1 ]]; then
-    printf "The first argument must be a valid algorithm\n" >&2
-    exit 1
-fi
+algorithm=${1:?missing algorithm}
 
-if ! printf "%s\n" "${algorithms[@]}" | grep -q "^$1$"; then
-    printf "Invalid algorithm: %s\n" "$1" >&2
+if ! printf "%s\n" "${algorithms[@]}" | grep -q "^$algorithm$"; then
+    printf "Invalid algorithm: %s\n" "$algorithm" >&2
     printf "Recognized algorithms: %s\n" "${algorithms[*]}" >&2
     exit 1
 fi
-
-algorithm=$1
 
 shift
 
diff --git a/files/home/.local/bin/enable-node b/files/home/.local/bin/enable-node
--- a/files/home/.local/bin/enable-node
+++ b/files/home/.local/bin/enable-node
@@ -15,13 +15,11 @@ git ls-remote --tags --refs "$REPO_URL" |
     sed -n "s:^.*refs/tags/v\(\S*\).*$:\1:p" |
     sort -r --version-sort >"$versions_file"
 
-if [[ ! -v 1 ]]; then
-    version=$(grep -vi -m1 '[a-z]' "$versions_file")
-elif ! grep -q "^$1$" "$versions_file"; then
-    printf "Invalid version: %s\n" "$1" >&2
+version=${1:-$(grep -vi -m1 '[a-z]' "$versions_file")}
+
+if ! grep -q "^$version$" "$versions_file"; then
+    printf "Invalid version: %s\n" "$version" >&2
     exit 1
-else
-    version=$1
 fi
 
 tag=v$version
