Tinkering

diff --git a/files/home/.local/bin/dateseq b/files/home/.local/bin/dateseq
--- a/files/home/.local/bin/dateseq
+++ b/files/home/.local/bin/dateseq
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # Return a sequence of dates.
-# Usage: dateseq TIMESTAMP INCREMENT COUNT [ARG...]
+# Usage: dateseq TIMESTAMP INCREMENT COUNT [ARGUMENT...]
 
 # The timestamp and increment parameters can be any string that `date`
 # recognizes as a time specification:
@@ -15,11 +15,35 @@
 # Get the UTC dates in ISO 8601 format for the first three months of 2001:
 # dateseq 2001-01-01 "+1 month" 3 --utc --iso-8601
 
-set -eu
+set -euo pipefail
 
-timestamp=${1:?missing initial timestamp}
-increment=${2:?missing increment}
-count=${3:?missing count}
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be a timestamp\n" >&2
+    exit 1
+fi
+
+timestamp=$1
+
+if [[ ! -v 2 ]]; then
+    printf "The second argument must be an increment\n" >&2
+    printf "See date(1) for more details\n" >&2
+    exit 1
+fi
+
+increment=$2
+
+if [[ ! -v 3 ]]; then
+    printf "The third argument must be a positive integer\n" >&2
+    exit 1
+fi
+
+if [[ $3 =~ [^0-9] ]] || (($3 < 1)); then
+    printf "Invalid count: %s (must be a positive integer)\n" "$3" >&2
+    exit 1
+fi
+
+count=$3
+
 shift 3
 
 normalize_timestamp() {
diff --git a/files/home/.local/bin/mkvbox b/files/home/.local/bin/mkvbox
--- a/files/home/.local/bin/mkvbox
+++ b/files/home/.local/bin/mkvbox
@@ -1,18 +1,67 @@
 #!/usr/bin/env bash
 
-# Create a new virtualbox guest.
-# Usage: mkvbox "Linux" linux.iso
-
-set -eu
-
-name=${1:?missing machine name}
-isofile=${2:?missing ISO file}
+set -euo pipefail
 
 ostype=${ostype:-Linux_64}
-memory=${memory:-4096}
+memory=${memory:-4}
 size=${size:-20}
 cpus=${cpus:-2}
 firmware=${firmware:-bios}
+
+usage="Create a new VirtualBox guest.
+
+Usage:
+    ${0##*/} [OPTIONS] NAME ISO_FILE
+
+Options:
+    -h           show this help text and exit
+
+    -o TYPE      specify operating system type
+                 (default: $ostype)
+
+    -m SIZE      specify memory size in gigabytes
+                 (default: $memory)
+
+    -s SIZE      specify main drive size in gigabytes
+                 (default: $size)
+
+    -c NUMBER    specify number of CPUs
+                 (default: $cpus)
+
+    -f TYPE      specify boot firmware type
+                 (default: $firmware)"
+
+while getopts ":o:m:s:c:f:h" option; do
+    case $option in
+    o) ostype=$OPTARG ;;
+    m) memory=$OPTARG ;;
+    s) size=$OPTARG ;;
+    c) cpus=$OPTARG ;;
+    f) firmware=$OPTARG ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
+    esac
+done && shift $((OPTIND - 1))
+
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be a machine name\n" >&2
+    exit 1
+fi
+
+name=$1
+
+if [[ ! -v 2 ]]; then
+    printf "The second argument must be an ISO file\n" >&2
+    exit 1
+fi
+
+iso_file=$2
 
 vmsdir=$(
     VBoxManage list systemproperties |
@@ -30,7 +79,7 @@ VBoxManage createvm \
     --name "$name" --ostype "$ostype" --register
 
 VBoxManage modifyvm "$name" \
-    --memory "$memory" --clipboard bidirectional \
+    --memory $((memory * 1024)) --clipboard bidirectional \
     --boot1 dvd --boot2 disk --boot3 none --boot4 none \
     --ioapic on --firmware "$firmware" --rtcuseutc on \
     --cpus "$cpus" --pae on --hwvirtex on \
@@ -40,10 +89,10 @@ VBoxManage modifyvm "$name" \
     --nic1 bridged --bridgeadapter1 "$bridgedif" \
     --defaultfrontend headless
 
-vdifile=$vmsdir/$name.vdi
+vdi_file=$vmsdir/$name.vdi
 
 VBoxManage createhd \
-    --filename "$vdifile" --size $((size * 1024))
+    --filename "$vdi_file" --size $((size * 1024))
 
 VBoxManage storagectl "$name" \
     --name "SATA Controller" \
@@ -52,7 +101,7 @@ VBoxManage storagectl "$name" \
 VBoxManage storageattach "$name" \
     --storagectl "SATA Controller" \
     --port 0 --device 0 --type hdd \
-    --medium "$vdifile"
+    --medium "$vdi_file"
 
 VBoxManage storagectl "$name" \
     --name "IDE Controller" --add ide
@@ -60,6 +109,6 @@ VBoxManage storagectl "$name" \
 VBoxManage storageattach "$name" \
     --storagectl "IDE Controller" \
     --port 0 --device 0 --type dvddrive \
-    --medium "$isofile"
+    --medium "$iso_file"
 
 VBoxManage snapshot "$name" take live
diff --git a/files/home/.zshrc.d/10-completions-plugin b/files/home/.zshrc.d/10-completions-plugin
--- a/files/home/.zshrc.d/10-completions-plugin
+++ b/files/home/.zshrc.d/10-completions-plugin
@@ -1,3 +1,9 @@
-. ~/.local/share/zsh/scripts/completions/zsh-completions.plugin.zsh
+file=$HOME/.local/share/zsh/scripts/completions/zsh-completions.plugin.zsh
+
+if ! . "$file"; then
+    printf "Unable to source file: %q\n" "$file" >&2
+fi
+
+unset file
 
 # vi:ft=zsh
diff --git a/files/home/.zshrc.d/10-syntax-plugin b/files/home/.zshrc.d/10-syntax-plugin
--- a/files/home/.zshrc.d/10-syntax-plugin
+++ b/files/home/.zshrc.d/10-syntax-plugin
@@ -1,3 +1,9 @@
-. ~/.local/share/zsh/scripts/syntax-highlighting/zsh-syntax-highlighting.zsh
+file=$HOME/.local/share/zsh/scripts/syntax-highlighting/zsh-syntax-highlighting.zsh
+
+if ! . "$file"; then
+    printf "Unable to source file: %q\n" "$file" >&2
+fi
+
+unset file
 
 # vi:ft=zsh
