Trying to find a naming that feels right

diff --git a/files/home/.local/bin/enable-deno b/files/home/.local/bin/enable-deno
--- a/files/home/.local/bin/enable-deno
+++ b/files/home/.local/bin/enable-deno
@@ -43,7 +43,7 @@ target=$machine-$kernel
 if [[ ! -f $archive ]]; then
     mkdir -p "$(dirname "$archive")"
     url=$REPO_URL/releases/download/v$version/deno-$target.zip
-    curl -L -o "$archive" "$url" || die "unable to download archive -- $url"
+    curl -L --progress-bar -o "$archive" "$url" || die "unable to download archive -- $url"
 fi
 
 if [[ -d $prefix ]]; then
diff --git a/files/home/.local/bin/enable-node b/files/home/.local/bin/enable-node
--- a/files/home/.local/bin/enable-node
+++ b/files/home/.local/bin/enable-node
@@ -34,7 +34,7 @@ machine=${machine/#x86_/x}
 if [[ ! -f $archive ]]; then
     mkdir -p "$(dirname "$archive")"
     url=https://nodejs.org/dist/v$version/node-v$version-$kernel-$machine.tar.xz
-    curl -L -o "$archive" "$url" || die "unable to download archive -- $url"
+    curl -L --progress-bar -o "$archive" "$url" || die "unable to download archive -- $url"
 fi
 
 if [[ -d $prefix ]]; then
diff --git a/files/home/.local/bin/enable-python b/files/home/.local/bin/enable-python
--- a/files/home/.local/bin/enable-python
+++ b/files/home/.local/bin/enable-python
@@ -29,7 +29,7 @@ archive=${XDG_CACHE_HOME:-$HOME/.cache}/python/python-$version.tar.gz
 if [[ ! -f $archive ]]; then
     mkdir -p "$(dirname "$archive")"
     url=$REPO_URL/archive/refs/tags/v${version}.tar.gz
-    curl -L -o "$archive" "$url" || die "unable to download archive -- $url"
+    curl -L --progress-bar -o "$archive" "$url" || die "unable to download archive -- $url"
 fi
 
 if [[ -d $prefix ]]; then
