Tinkering

diff --git a/files/home/.local/bin/init-node b/files/home/.local/bin/init-node
--- a/files/home/.local/bin/init-node
+++ b/files/home/.local/bin/init-node
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # Initialize a Node.js prefix.
-# Usage: init-node VERSION
+# Usage: init-node VERSION [DIRECTORY]
 
 set -eu
 
@@ -11,24 +11,19 @@ die() {
 }
 
 version=${1:?missing version}
-
-git ls-remote --tags --refs https://github.com/nodejs/node |
-    grep -q "refs/tags/v${version}$" || die "invalid version -- $version"
-
-archive_file=${XDG_CACHE_HOME:-$HOME/.cache}/node/node-$version.tar.gz
+prefix=${2:-${XDG_DATA_HOME:-$HOME/.local/share}/node/$version}
+archive=${XDG_CACHE_HOME:-$HOME/.cache}/node/node-$version.tar.gz
 
 kernel=$(uname --kernel-name)
 kernel=${kernel,,}
 machine=$(uname --machine)
 machine=${machine/86_/}
 
-if [[ ! -f $archive_file ]]; then
-    mkdir -p "$(dirname "$archive_file")"
+if [[ ! -f $archive ]]; then
+    mkdir -p "$(dirname "$archive")"
     url=https://nodejs.org/dist/v$version/node-v$version-$kernel-$machine.tar.xz
-    curl -L -o "$archive_file" "$url" || die "unable to download archive -- $url"
+    curl -L -o "$archive" "$url" || die "unable to download archive -- $url"
 fi
-
-prefix=${XDG_DATA_HOME:-$HOME/.local/share}/node/$version
 
 if [[ ! -d $prefix ]]; then
     temp_dir=$(mktemp -d -t "${0##*/}.XXXXXXXXXX")
@@ -36,7 +31,7 @@ if [[ ! -d $prefix ]]; then
     trap "$cleanup" INT TERM EXIT
 
     cd "$temp_dir"
-    tar -xf "$archive_file"
+    tar -xf "$archive"
     mkdir -p "$(dirname "$prefix")"
     mv "node-v${version}-${kernel}-${machine}" "$prefix"
 fi
diff --git a/files/home/.local/bin/init-python b/files/home/.local/bin/init-python
--- a/files/home/.local/bin/init-python
+++ b/files/home/.local/bin/init-python
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # Initialize a Python prefix.
-# Usage: init-python VERSION
+# Usage: init-python VERSION [DIRECTORY]
 
 set -eu
 
@@ -10,22 +10,15 @@ die() {
     exit "${2:-1}"
 }
 
-repo_url=https://github.com/python/cpython
-
 version=${1:?missing version}
+prefix=${2:-${XDG_DATA_HOME:-$HOME/.local/share}/python/$version}
+archive=${XDG_CACHE_HOME:-$HOME/.cache}/python/python-$version.tar.gz
 
-git ls-remote --tags --refs "$repo_url" |
-    grep -q "refs/tags/v${version}$" || die "invalid version -- $version"
-
-archive_file=${XDG_CACHE_HOME:-$HOME/.cache}/python/python-$version.tar.gz
-
-if [[ ! -f $archive_file ]]; then
-    mkdir -p "$(dirname "$archive_file")"
-    url=$repo_url/archive/refs/tags/v${version}.tar.gz
-    curl -L -o "$archive_file" "$url" || die "unable to download archive -- $url"
+if [[ ! -f $archive ]]; then
+    mkdir -p "$(dirname "$archive")"
+    url=https://github.com/python/cpython/archive/refs/tags/v${version}.tar.gz
+    curl -L -o "$archive" "$url" || die "unable to download archive -- $url"
 fi
-
-prefix=${XDG_DATA_HOME:-$HOME/.local/share}/python/$version
 
 if [[ ! -d $prefix ]]; then
     temp_dir=$(mktemp -d -t "${0##*/}.XXXXXXXXXX")
@@ -33,7 +26,7 @@ if [[ ! -d $prefix ]]; then
     trap "$cleanup" INT TERM EXIT
 
     cd "$temp_dir"
-    tar -xf "$archive_file"
+    tar -xf "$archive"
     cd cpython-"$version"
 
     ./configure --prefix="$prefix" --enable-optimizations
@@ -56,5 +49,5 @@ pip install --upgrade pip
 packages_file=${PYTHON_DEFAULT_PACKAGES:-$HOME/.default-python-packages}
 
 if [[ -f $packages_file ]]; then
-    pip install --upgrade --requirement "$packages_file"
+    xargs -r pip install --upgrade <"$packages_file"
 fi
