Tinkering

diff --git a/files/home/.local/bin/mangrep b/files/home/.local/bin/mangrep
--- a/files/home/.local/bin/mangrep
+++ b/files/home/.local/bin/mangrep
@@ -4,8 +4,54 @@
 
 set -euo pipefail
 
+usage="Search the complete text of all man pages.
+
+Usage:
+    ${0##*/} [OPTIONS] [ARGUMENT...]
+
+Options:
+    -h         show this help text and exit
+    -s NAME    narrow search to section NAME (can be used multiple times)
+
+Arguments:
+    ARGUMENT    argument to pass on to zgrep"
+
+section_options=()
+
+while getopts ":s:h" option; do
+    case $option in
+    s) section_options+=(-o -name "*.$OPTARG.?*") ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    :)
+        printf "Option missing argument: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
+    esac
+done && shift $((OPTIND - 1))
+
 # Split path string used by man into an array of directories.
 IFS=: read -r -d "" -a dirs < <(printf "%s:\0" "$(man -w)")
 
+dirs_that_exist=()
+
+for dir in "${dirs[@]}"; do
+    if [[ -d $dir ]]; then
+        dirs_that_exist+=("$dir")
+    fi
+done
+
+find_options=()
+
+if ((${#section_options[@]} > 0)); then
+    find_options+=(\( "${section_options[@]:1}" \))
+fi
+
 # Search all the (possibly compressed) man pages in those directories.
-find "${dirs[@]}" -type f -print0 | xargs -r0 zgrep -l -m1 "$@"
+find "${dirs_that_exist[@]}" -type f "${find_options[@]}" -print0 | xargs -r0 zgrep -l -m1 "$@"
diff --git a/files/home/.local/bin/previewer b/files/home/.local/bin/previewer
--- a/files/home/.local/bin/previewer
+++ b/files/home/.local/bin/previewer
@@ -2,23 +2,23 @@
 
 set -euo pipefail
 
-usage="Show a preview of the given file.
+usage="Show a preview of the given path.
 
 Usage:
-    ${0##*/} [OPTIONS] FILE
+    ${0##*/} [OPTIONS] PATH
 
 Options:
-    -h           show this help text and exit
-    -l NUMBER    highlight line NUMBER (if supported)
+    -h             show this help text and exit
+    -g LOCATION    go to a specific location (if supported)
 
 Arguments:
-    FILE         the file to preview"
+    PATH           the file/directory/URL to preview"
 
-unset line_number
+unset goto
 
-while getopts ":l:h" option; do
+while getopts ":g:h" option; do
     case $option in
-    l) line_number=$OPTARG ;;
+    g) goto=$OPTARG ;;
     h)
         printf "%s\n" "$usage"
         exit 0
@@ -34,61 +34,88 @@ while getopts ":l:h" option; do
     esac
 done && shift $((OPTIND - 1))
 
-target=${1:?missing file/URL}
+is_positive_int() {
+    local value=$1
+    [[ $value =~ ^[0-9]+$ ]] && ((value > 0))
+}
 
-if [[ $target == file://* ]]; then
-    target=${target#file://}
-    target=${target//+/ }
-    target=${target//%/\\x}
-    printf -v target "%b" "$target"
+ensure_positive_int() {
+    local value=${1:-${2:-1}}
+    if ! is_positive_int "$value"; then
+        printf "Invalid value: %s (must be a positive integer)\n" "$value" >&2
+        exit 1
+    fi
+    printf "%s" "$value"
+}
+
+path=${1:?missing file/URL}
+
+if [[ $path == file://* ]]; then
+    path=${path#file://}
+    path=${path//+/ }
+    path=${path//%/\\x}
+    printf -v path "%b" "$path"
 fi
 
-mime_type=$(file --dereference --brief --mime-type "$target")
+if [[ $path == *://* ]]; then
+    exec curl --silent --show-error --location --head "$path"
+fi
 
-filename=$(basename "$target")
+if [[ -d $path ]]; then
+    exec ls -l -- "$path"
+fi
+
+mime_type=$(file --dereference --brief --mime-type "$path")
+
+filename=$(basename "$path")
 ext=${filename##*.}
 ext=${ext,,}
 
 if [[ $ext =~ ^(7z|ace|ar|arc|bz2?|cab|cpio|cpt|deb|dgc|dmg|gz|jar|msi|pkg|rar|shar|tar|tgz|xar|xpi|xz|zip|zst)$ ]]; then
-    exec als -- "$target"
+    exec als -- "$path"
 fi
 
 if [[ $ext == torrent ]]; then
-    exec transmission-show -- "$target"
+    exec transmission-show -- "$path"
 fi
 
 if [[ $ext == pdf || $mime_type == application/pdf ]]; then
-    exec pdftotext -l 10 -nopgbrk -q -- "$target" -
+    exec pdftotext -l 10 -nopgbrk -q -- "$path" -
 fi
 
 if [[ $ext =~ ^(od[spt]|sxw)$ ]]; then
-    exec odt2txt -- "$target"
+    exec odt2txt -- "$path"
 fi
 
 if [[ $ext =~ ^(docx?)$ ]]; then
-    exec catdoc -- "$target"
+    exec catdoc -- "$path"
 fi
 
 if [[ $ext =~ ^(ppt?)$ ]]; then
-    exec catppt -- "$target"
+    exec catppt -- "$path"
 fi
 
 if [[ $ext =~ ^xlsx?$ ]]; then
-    exec xls2csv -- "$target"
+    exec xls2csv -- "$path"
 fi
 
 if [[ $ext == json || $mime_type == application/json ]]; then
-    exec jq --color-output . -- "$target"
+    exec jq --color-output . -- "$path"
 fi
 
 if [[ $mime_type =~ ^(image|audio|video)/ ]]; then
-    exec mediainfo -- "$target"
+    exec mediainfo -- "$path"
 fi
 
 if [[ $ext =~ ^(mk?d|markdown)$ ]]; then
-    exec mdcat --no-pager -- "$target"
+    exec mdcat --no-pager -- "$path"
 fi
 
 if [[ $mime_type =~ ^text/ ]]; then
-    exec bat --color always --paging never ${line_number:+--highlight-line $line_number} -- "$target"
+    exec bat --color=always --paging=never \
+        ${goto:+--highlight-line="$(ensure_positive_int "$goto")"} \
+        -- "$path"
 fi
+
+printf "Unrecognized path: %q\n" "$path" >&2
+exit 9
