Simplify script

diff --git a/files/home/.local/bin/pastebin b/files/home/.local/bin/pastebin
--- a/files/home/.local/bin/pastebin
+++ b/files/home/.local/bin/pastebin
@@ -1,22 +1,39 @@
 #!/usr/bin/env bash
 
-# Paste lines to a shareable URL.
-# Usage: pastebin /path/to/file...
-#        command-with-output | pastebin
-
 set -euo pipefail
 
-send() {
-    curl -sSL --data-binary @"$1" https://paste.rs
-}
+usage="Paste text to a shareable URL.
 
-if (($# == 0)); then
-    send /dev/stdin
-else
-    for file in "$@"; do
-        ext=${file##*/}
-        ext=${ext##*.}
-        url=$(send "$file")
-        printf "%s%s\n" "$url" "${ext:+.$ext}"
-    done
+Usage:
+    pastebin [OPTIONS] [FILE]
+
+Options:
+    -h         show this help text and exit
+    -t TYPE    explicitly set file type to TYPE"
+
+unset ext
+
+while getopts ":t:h" option; do
+    case $option in
+    t) ext=$OPTARG ;;
+    h)
+        printf "%s\n" "$usage"
+        exit 0
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
+    esac
+done && shift $((OPTIND - 1))
+
+file=${1:-/dev/stdin}
+
+url=$(curl -sSL --data-binary @"$file" https://paste.rs)
+
+if [[ ! -v ext ]]; then
+    ext=${file##*/}
+    ext=${ext##*.}
 fi
+
+printf "%s%s\n" "$url" "${ext:+.$ext}"
