Ensure path does not contain newlines

diff --git a/files/home/.local/bin/secrets b/files/home/.local/bin/secrets
--- a/files/home/.local/bin/secrets
+++ b/files/home/.local/bin/secrets
@@ -24,16 +24,25 @@ Actions:
 If the store directory is a git repository, each change will be committed."
 
 get_file() {
-    printf "%s/%s.age" "$store_dir" "$1"
+    local file=$store_dir/$1.age
+
+    if [[ $file == *$'\n'* ]]; then
+        printf "Invalid file path: %q (contains newline)\n" "$file" >&2
+        exit 1
+    fi
+
+    printf "%s" "$file"
 }
 
 assert_file() {
     local file
     file=$(get_file "$1")
+
     if [[ ! -f $file || ! -r $file ]]; then
         printf "File does not exist or is not readable: %q\n" "$file" >&2
         return 1
     fi
+
     printf "%s" "$file"
 }
 
